### ISSUE TITLE
Flutter 2.0.1 compatibility

### ISSUE THREAD

**Issue by iamwilph** [emanuel-braz/one_context#13]
Got this build error message in one of my apps: "since your app depends on both one_context ^0.5.0 and shared_preferences ^2.0.3, version solving failed". Using older versions of shared_preferences will also result in a "version solving problem" with the other packages.

**Comment by sergiotucano** [comment]
+1

These error occurs because the package don't is Null safety

**Comment by phanvanluan94** [comment]
+1
Same issue.

**Comment by emanuel-braz** [comment]
I released the null safety version today, please upgrade to the new version 1.0.0

@iamwilph @sergiotucano @phanvanluan94 

![image](https://user-images.githubusercontent.com/3827308/111255844-9731bb80-85f6-11eb-9190-6017aadf7c87.png)

**Comment by iamwilph** [comment]
thanks!
