### ISSUE TITLE
Can I use one_context to optimize my app size?

### ISSUE THREAD

**Issue by fonkamloic** [emanuel-braz/one_context#17]
I was amazed at finding this package. My recurrent problem of app size just came to mind. 

```// Set the main() function
void main() => OnePlatform.app = () => LiteAppInstall();  // 5mb

// Later... Call reboot without recreating root app
OnePlatform.reboot();

// Later... Call reboot recreating the entire application
OnePlatform.reboot(
  builder: () => MainApp()    // 15Mb
);

// You even can load an entire different app
OnePlatform.reboot(
  builder: () => MyAppPremium().  //40Mb
);```

From the example above, Is it possible to externalize  MainApp and MyAppPremium for lazy downloaded if need by the user?
So my intention is to have my app listed on AppStore and Playstore as being ~= 5Mb in size.

**Comment by emanuel-braz** [comment]
Hi @fonkamloic, 

Unfortunately, it's not to supposed to work like that. Actually, the feature you are looking for "Code Push", is not available in flutter toolkit yet. 
And the current feature, drives you to increase size the app mixing multiple app logic(or maybe, you can share assets and codebase, reducing the app size instead to all versions in the same binary). It depends of your needs.

You can embed multiple different app logic, but all of those, should be compiled together. This package do not enable you to download the code later and run JIT code.

If you need to update/download the logic of your app later, without increase the binary size, consider using webview. It's not the good choice for performance goals indeed.

Take a look on discussion [Code push issue - Flutter](https://github.com/flutter/flutter/issues/14330#issue-292552503)

**Comment by fonkamloic** [comment]
Hi @emanuel-braz,

Thank you for your prompt response. Code push or any hack to achieve it is what I am aiming at. Thanks for putting me on the right path.
