### ISSUE TITLE
change modal backdrop color

### ISSUE THREAD

**Issue by riyanto978** [emanuel-braz/one_context#25]
hello, how to change backdrop modal color?

**Comment by emanuel-braz** [comment]
Hello @riyanto978 , the package is outdated, I gonna update it today, ok?

For instance, you will be able to change `barrierColor` this way:

```dart
OneContext().showDialog<String>(
  barrierColor: Colors.purple.withOpacity(.4),
  builder: (context) => new SimpleDialog()
);
```

**Comment by emanuel-braz** [comment]
@riyanto978 pls update to version 2.1.0
