### ISSUE TITLE
Problems with the snackbar

### ISSUE THREAD

**Issue by titoworlddev** [emanuel-braz/one_context#28]
Basically my problem is because I just wanted to use OneContext to display a snackbar since I found the package recently and it said it's so easy that I thought I'd use it.
But my surprise is when I simply execute the method shown in the README of the pub.dev page
```
// example snackBar
OneContext().showSnackBar(
     builder: (_) => SnackBar(content: Text('My awesome snackBar!'))
);
```

but it gave me an error that told me that I have to put a builder in the MaterialApp to have the context
```
return MaterialApp(
       builder: OneContext().builder,
       ....
```

That is why I come to create this error to ask that the package instructions be done correctly since it is being said that it is so easy and in the first test that I do it gives me an error.

It would be nice to explain that in order to have a global context, OneContext().builder must be used in the MaterialApp builder.

**Comment by emanuel-braz** [comment]
Hi @titoworlddev, thanks for the feedback, but I would like to ask you to read the documentation as it contains the information you quoted. I believe the error displayed also describes what you need to do to get it working.

If you follow the readme instructions, and it does not works, please let me know.

![Screen Shot 2022-08-19 at 13 54 04](https://user-images.githubusercontent.com/3827308/185713091-5ee00f45-149d-41c3-9003-650aa81d8275.png)

**Comment by titoworlddev** [comment]
Hello, yes it's true, sorry, really I was looking for it and I couldn't find it. I do not know what happened to me.

Anyway I think it would be one of the first things that should be said.

Likewise, once you use it well, the package is great, thanks for the contribution.
