### ISSUE TITLE
Gorouter navigation breaks when OneContext.builder is used in material app

### ISSUE THREAD

**Issue by ricksondpenha** [emanuel-braz/one_context#31]
Flutter web navigation breaks when using OneContext.builder() in material app. I'm using gorouter for navigation, the browser back button doesnt work anymore..

**Comment by ricksondpenha** [comment]
I've created a minimal reproducible example here.. [Repo Link](https://github.com/ricksondpenha/onecontext_webnav_bug)

I've tried linking OneContext().key to the gorouter object but no luck.. any pointers would help

**Comment by emanuel-braz** [comment]
This package is not compatible with GoRouter. I will update it to be able to use GoRouter.
In order to keep compatibility, I will create a different register way to use GoRouter.

**Comment by ricksondpenha** [comment]
Hi, just a follow up with this issue... any progress or fix for this? really need it for the web app we are building.
