### ISSUE TITLE
Already a builder in MaterialApp

### ISSUE THREAD

**Issue by rj76** [emanuel-braz/one_context#33]
Hello,

I'm trying to use your package, but it needs the builder of MaterialApp set to `builder: OneContext().builder` and I already have a custom builder set in my app. Is there a workaround for this?

**Comment by shahmirzali49** [comment]
+1

**Comment by emanuel-braz** [comment]
```dart
builder: (context, widget) {
   // some code
   final resultWidget = OneContext().builder(context, widget, mediaQueryData: MediaQuery.of(context).copyWith(textScaleFactor: 1.0));
   return resultWidget;
}
```

**Comment by emanuel-braz** [comment]
This issue is being closed due to inactivity.
