### ISSUE TITLE
routeName always return null

### ISSUE THREAD

**Issue by gushedaoren** [emanuel-braz/one_context#34]
OneContext().popUntil((route) {
            var name=route.settings.name;

            print("routeName:$name");
            return true;
          });

        routeName:null

**Comment by emanuel-braz** [comment]
The problem is because you are not passing route settings to MaterialPageRoute in router.

```dart
MaterialPageRoute(
          settings: settings, builder: (context) => SplashScreen());
```

ref: https://stackoverflow.com/questions/63772579/routes-returning-null-while-calling-popuntil-on-globalkeynavigatorstate
