### ISSUE TITLE
Please update the package to most latest version of the flutter

### ISSUE THREAD

**Issue by moinkhan780** [emanuel-braz/one_context#37]
Need update please

**Comment by moinkhan780** [comment]
No response ?

**Comment by emanuel-braz** [comment]
ok, lets do this!

**Comment by emanuel-braz** [comment]
Working on this PR #39

### Done
- Migration to dart 3

### Doing
- refactoring, doc/changelog and tests

**Comment by emanuel-braz** [comment]
New version released [pub.dev 3.0.0-rc-1](https://pub.dev/packages/one_context/versions/3.0.0-rc-1)

@moinkhan780 I tested the package a lot after the refactoring, but if you can help with testing it too I would really appreciate it 🙌

`one_context: ^3.0.0-rc-1`
