### ISSUE TITLE
When you will release the updated version! 

### ISSUE THREAD

**Issue by moinkhan780** [emanuel-braz/one_context#38]
Some latest features are missing please update package. 

For example showDragHandle is available in latest version of flutter. and also some other features also

`showModalBottomSheet(
      showDragHandle: true,
      context: context,
      builder: (context) {
        return Container(
          padding: const EdgeInsets.all(16.0),
          child: ListView.builder(
            itemCount: _ingredientList.length,
            itemBuilder: (context, index) {
              final ingredient = _ingredientList[index];
              return ListTile(
                title: Text(ingredient),
                onTap: () {
                  completer.complete(ingredient);
                  Navigator.pop(context); // Close the bottom sheet after selecting an ingredient
                },
              );
            },
          ),
        );
      },
    );`

**Comment by emanuel-braz** [comment]
I will work on it this weekend

**Comment by emanuel-braz** [comment]
Closing as duplicate of https://github.com/emanuel-braz/one_context/issues/37
