### ISSUE TITLE
nullOk removed from flutter Navigator.of method

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [emanuel-braz/one_context#8]
Thanks for the plugin.

It has stopped working on the beta branch as flutter team has removed the nullok parameter from the Navigator class.

FYI - https://flutter.dev/go/eliminating-nullok-parameters

I think we need to update the navigatorOf in navigator_controller.mixin.dart and remove the nullOk parameter.

![image](https://user-images.githubusercontent.com/10863510/102488529-2da31f00-4092-11eb-8aad-b8f8c4acfc0d.png)

I have created https://github.com/emanuel-braz/one_context/pull/9 PR for the same.

**Comment by emanuel-braz** [comment]
Hi @sawankumarbundelkhandi  I will check the PR and accept it as soon as possible if everything is ok.
Thank you very much for the support!

**Comment by emanuel-braz** [comment]
Issue solved with PR #9 and published on pud.dev with PR #10 
Thanks @sawances
